### PR TITLE
Add post for Lissted

### PR DESCRIPTION
**Pull request by ynnoj**

### CODE REVIEW

**Comment by mansona** [comment]
:+1:

**Comment by gcollazo** [comment]
Please change the link to the homepage and change the date to publish.

**Comment by ynnoj** [comment]
@gcollazo What do you mean by publish? Should I change to today's date?

**Comment by mansona** [comment]
@ynnoj I just pushed a change that I think fixes what @gcollazo was talking about... @gcollazo can you let me know if you need any other changes

**Comment by gcollazo** [comment]
Looks good. I will publish on Monday. Thanks :)

**Pull request merged**
