### PR TITLE
Add Glamping Hub

### PR DESCRIPTION
**Pull request by ablanco**

### CODE REVIEW

**Comment by RobbieTheWagner** [comment]
Thanks for the PR @ablanco! Does the site still use Ember? Is it only once you log in? I went to the homepage and it didn't appear to use Ember.

**Comment by ablanco** [comment]
Hi. Yes, we still use Ember.js, but we use it in the users' private dashboard, not on the public site. Only registered users or users that have placed a booking can access the Ember app.

We're currently rebuilding the dashboard following a new design, the current one is an Ember 1.13, and the new one is being built with Ember 3.0.0

**Review by RobbieTheWagner — APPROVED** [review]
This looks good to me. @gcollazo how strict are we on the screenshot dimensions? The ratio may be a bit off here.

**Comment by gcollazo** [comment]
@rwwagner90 width is strict but height might be a little bit more.

**Comment by RobbieTheWagner** [comment]
@gcollazo so the width here appears to be 1200, but we want 1000 right?

**Comment by gcollazo** [comment]
@rwwagner90 1000×800 is what we suggest on the README file

**Comment by RobbieTheWagner** [comment]
Right, so this needs to be updated. @ablanco can you get a 1000x800 screenshot please?

**Comment by ablanco** [comment]
I've updated the image, it's now 1000x800

**Comment by RobbieTheWagner** [comment]
Awsome, thanks @ablanco!

**Pull request merged**
