### PR TITLE
Add BBVA

### PR DESCRIPTION
**Pull request by shokmaster**
The BBVA mobile app.

https://movil.bbva.es

### CODE REVIEW

**Comment by gcollazo** [comment]
Hi @shokmaster I would gladly accept your PR but first:

- [ ] Make sure you add the `is_mobile` setting [like this](https://raw.githubusercontent.com/GetBlimp/built-with-ember/gh-pages/_posts/2016-08-03-gasolinamovil.md)
- [ ] Make sure the image does not include "the phone" [like this](https://raw.githubusercontent.com/GetBlimp/built-with-ember/gh-pages/screenshots/gasolina-movil.png)
- [ ] Process the screenshot using https://tinypng.com/

**Comment by shokmaster** [comment]
Done:

- [x]  Make sure you add the `is_mobile` setting
- [x]  Make sure the image does not include "the phone"
- [x]  Process the screenshot using https://tinypng.com/

Thanks!

**Comment by gcollazo** [comment]
@shokmaster Ya está arriba, gracias!

**Comment by shokmaster** [comment]
Thank u @gcollazo !!

**Pull request merged**
